dist: trusty
sudo: required

language: c

os:
  - linux

compiler:
  - gcc

addons:
  apt:
    update: true
    packages:
      - valgrind
      - cppcheck

script:
  - mkdir build
  - cd build
  - cmake ..
<<<<<<< HEAD
  - valgrind --tool=memcheck --leak-check=summary ./tests
=======
>>>>>>> origin/make-hw1









  cppcheck -q --enable=all --inconclusive ./srcсзз