dist:     trusty
sudo:     required

language: cpp

os:
  - linux

compiler:
  - gcc

addons:
  apt:
    update: true
    packages:
      - valgrind
      - cppcheck

script:
  - mkdir build
  - cd build
  - cmake ..
  - cppcheck -q --enable=all --inconclusive ./src
  - valgrind --tool=memcheck --leak-check=summary ./tests