dist:     trusty
sudo:     required

language: c

os:
  - linux

compiler:
  - gcc

addons:
  apt:
    update: true
    packages:
      - valgrind
      - cppcheck

install:
  - sudo apt-get install libgtest-dev
  - cd /usr/src/gtest
  - ls
  - sudo cmake CMakeLists.txt
  - sudo make
  - sudo make install
  - mkdir build
  - cd build
  - cmake ..

script:
  - cppcheck -q --enable=all --inconclusive ../src
  - valgrind --tool=memcheck --leak-check=summary ./tests