dist:     trusty
sudo:     required

language: c

os:
  - linux

compiler:
  - gcc

addons:
  apt:
    update: true
    packages:
      - valgrind
      - cppcheck
      - cmake
      - libgtest-dev

install:
  - cd /usr/src/gtest
  - sudo cmake CMakeLists.txt
  - sudo make
  - sudo make install
  - cd /home/travis/build/piklin/cpp_homeworks_park.mail

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - cppcheck -q --enable=all ../src
  - valgrind --tool=memcheck --leak-check=full ./tests