dist:     trusty
sudo:     required

language: c

os:
  - linux

compiler:
  - gcc

addons:
  apt:
    update: true
    packages:
      - valgrind
      - cppcheck

install:
  - sudo apt-get install libgtest-dev
  - cd /usr/src/gtest
  - sudo cmake CMakeLists.txt
  - sudo make
  - sudo cp *.a /usr/lib
  - cd ~

script:
  - mkdir build
  - cd build
  - cmake ..
  - cppcheck -q --enable=all --inconclusive ../src
  - valgrind --tool=memcheck --leak-check=summary ./tests