dist:     trusty
sudo:     required

language: c

os:
  - linux

compiler:
  - gcc

addons:
  apt:
    update: true
    packages:
      - valgrind
      - cppcheck
      - cmake
      - libgtest-dev

install:
  - cd /usr/src/gtest
  - sudo cmake CMakeLists.txt
  - sudo make
  - sudo cp *.a /usr/lib
  - cd /home/travis/build/piklin/cpp_homeworks_park.mail/hw2/
  - cppcheck -q --enable=all -inconclusive ./search_libs
  - cppcheck -q --enable=all -inconclusive ./search_example

script:
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build .
  - ./search_example/parallel_search_example 100000000
  - ./search_example/sequential_search_example 100000000
  - valgrind --tool=memcheck --leak-check=full ./search_libs/common_files_tests
  - bash <(curl -s https://codecov.io/bash)